language: rust

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=riscv32imac-unknown-none-elf

rust:
  - nightly
  - stable

if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)


install:
  - ci/install.sh

script:
  - ci/script.sh


cache: cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
